# Generated by Django 2.1.7 on 2019-06-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description_short',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
