# Generated by Django 2.1.7 on 2019-06-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Review',
        ),
    ]
